server:
  port : 3030
spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql